IF db_id('LS2') IS NULL CREATE DATABASE LS2;

GO
USE LS2

IF object_id('TICKET') IS NOT NULL DROP TABLE TICKET
IF object_id('CINEMA_SESSION') IS NOT NULL DROP TABLE CINEMA_SESSION
IF object_id('THEATER') IS NOT NULL DROP TABLE THEATER
IF object_id('MOVIE') IS NOT NULL DROP TABLE MOVIE
IF object_id('CINEMA') IS NOT NULL DROP TABLE CINEMA

