IF db_id('LS2') IS NULL CREATE DATABASE LS2;

GO
USE LS2


CREATE TABLE MOVIE (
	Mid INT identity (1,1),
	Title VARCHAR(25) UNIQUE NOT NULL,
	Release_Year INT NOT NULL,
	Duration INT NOT NULL,
	PRIMARY KEY (Mid)
);


CREATE TABLE CINEMA (
	Cid INT IDENTITY (1,1),
	Name VARCHAR(25) UNIQUE NOT NULL,
	City VARCHAR(25) NOT NULL,
	PRIMARY KEY (Cid)
);


CREATE TABLE THEATER (
	Tid INT IDENTITY (1,1),
	nSeats INT NOT NULL,
	nRows INT NOT NULL,
	SeatsPerRow INT NOT NULL,
	Theater_Name VARCHAR(25) NOT NULL,
	Cid INT REFERENCES CINEMA(Cid),
	PRIMARY KEY (Tid)
);


CREATE TABLE CINEMA_SESSION(
	Sid INT IDENTITY (1,1),
	Date DATE NOT NULL,
	Mid INT REFERENCES MOVIE(Mid),
	Tid INT REFERENCES THEATER(Tid),
	PRIMARY KEY (Sid)
);