IF db_id('LS2') IS NULL CREATE DATABASE LS2;

GO
USE LS2


CREATE TABLE MOVIE (
	mid INT IDENTITY (1,1),
	Title VARCHAR(25) UNIQUE NOT NULL,
	Release_Year INT NOT NULL,
	Duration INT NOT NULL,
	PRIMARY KEY (mid)
);


CREATE TABLE CINEMA (
	cid INT IDENTITY (1,1),
	Name VARCHAR(25) UNIQUE NOT NULL,
	City VARCHAR(25) NOT NULL,
	PRIMARY KEY (cid)
);


CREATE TABLE THEATER (
	tid INT IDENTITY (1,1),
	SeatsAvailable INT NOT NULL,
	Rows INT NOT NULL,
	Seats INT NOT NULL,
	Theater_Name VARCHAR(25) NOT NULL,
	cid INT REFERENCES CINEMA(cid),
	PRIMARY KEY (tid)
);

CREATE TABLE SEATS(
	seats int,
	tid int references THEATER(tid),
	sid int references CINEMA_SESSION(sid),
	primary key(tid, sid)
);


CREATE TABLE CINEMA_SESSION(
	sid INT IDENTITY (1,1),
	Date DATETIME NOT NULL,
	mid INT REFERENCES MOVIE(mid),
	tid INT REFERENCES THEATER(tid),
	PRIMARY KEY (sid)
);

CREATE TABLE TICKET(
	tkid VARCHAR(3),
	seat INT NOT NULL,
	row CHAR NOT NULL,
	sid INT REFERENCES CINEMA_SESSION(sid),
	PRIMARY KEY (sid, tkid)
);


INSERT INTO MOVIE VALUES('titulo1', 2000, 90)
INSERT INTO CINEMA VALUES('CinemaNome1', 'city1')
INSERT INTO THEATER VALUES(100, 10, 10, 'sala1', 1) --1
INSERT INTO THEATER VALUES(100, 10, 10, 'sala2', 1) --2
INSERT INTO CINEMA_SESSION VALUES('2018-04-21 20:00', 1, 1)--1
INSERT INTO CINEMA_SESSION VALUES('2018-04-21 17:00', 1, 1)--2 duas sessoes na sala1
INSERT INTO CINEMA_SESSION VALUES('2018-04-21 17:00', 1, 2)--3
INSERT INTO TICKET VALUES('A1', 1, 'A', 1)
INSERT INTO TICKET VALUES('A2', 2, 'A', 1) --dois tickets para a sessao 1
INSERT INTO TICKET VALUES('A1', 1, 'A', 2)
INSERT INTO TICKET VALUES('A2', 2, 'A', 2)--dois tickets para a sessao 2
INSERT INTO TICKET VALUES('A1', 1, 'A', 3)


SELECT * FROM TICKET
SELECT * FROM MOVIE
SELECT * FROM CINEMA_SESSION
SELECT * FROM THEATER
SELECT * FROM CINEMA
SELECT * FROM SEATS

